### ISSUE TITLE
Translate zhCN.lua strings

### ISSUE THREAD

**Issue by tilkinsc** [tilkinsc/KiwiItemInfo#15]
In `Locale/zhCN.lua` some strings aren't translated fully.

在`Locale/zhCN.lua`中，某些字符串未完全翻译。

**Comment by hu71e** [comment]
Corrected some incorrect formatting in zhCN.lua, some localized translations have been added  and passed the test under version 2.2.5, But iLvl still can not be displayed.

[zhCN.lua.txt](https://github.com/tilkinsc/KiwiItemInfo/files/3765776/zhCN.lua.txt)

**Comment by tilkinsc** [comment]
Hover over a weapon/armor and do `/dump GameTooltipTextRight1:GetText()`
Also, disable 'could be problem' addons and see if that fixes it.

**Comment by hu71e** [comment]
<img width="249" alt="dumpTooltipText" src="https://user-images.githubusercontent.com/16714185/67537042-589f1680-f70c-11e9-8bbe-01208b9467c1.png">

Empty result

<img width="267" alt="dump_noaddons" src="https://user-images.githubusercontent.com/16714185/67537167-ca776000-f70c-11e9-967c-c4c7511a63cc.png">

Empty result too, no AddOns loaded but kiwi.

**Comment by tilkinsc** [comment]
Aha. This is expected. Because you are using a bag addon, `GetMouseFocus()` never pops correctly. So it results in a return. 
![image](https://user-images.githubusercontent.com/7494772/67537359-ffea6200-f6a8-11e9-847d-e74a666fd271.png)
Because the item couldn't be figured out, nothing became of it.

**Comment by hu71e** [comment]
The second time I just used the kiwi AddOns, I got the same empty result. why？

**Comment by tilkinsc** [comment]
`/dump GameTooltipTextRight1` gives results right?

**Comment by hu71e** [comment]
<img width="739" alt="dump" src="https://user-images.githubusercontent.com/16714185/67537971-22639600-f710-11e9-86bc-1d15d3ccf16a.png">

Dump: GameTooltipTextRight1 
GameTooltipTextRight1={ 
  [0]=<userdata GameTooltipTextRight1[0]> 
}

**Comment by tilkinsc** [comment]
Then you should be able to `GameTooltipTextRight1:SetText("ilvl 50")` and it would display text.

So yeah... has to be something to do in my function. I would like to confirm that the above code works, also.

I would probably have you print out the values of itemLevel, itemType, focus, name, i_name, i_link, as these are what prevents it from working

**Comment by hu71e** [comment]
How to do it? /dump? return the empty result.

**Comment by tilkinsc** [comment]
`/run GameTooltipTextRight1:SetText("ilvl 50")` (ofc have to hover the tooltip first)

/dump is the equiv of `/run return ...` where the return pretty prints things out.

**Comment by tilkinsc** [comment]
![image](https://user-images.githubusercontent.com/7494772/67560501-04366f80-f6e9-11e9-9e1d-5f4228c8f238.png)
idk man... works for me

Ahh. I see the problem. It only shows when `/kiwiii set ilvl_only_equips true`

LOL. Ok... so we got a compatibility issue... 
![image](https://user-images.githubusercontent.com/7494772/67562942-afe1be80-f6ed-11e9-8828-7017bc111644.png)

This is what it shows me when I print `itemType` ... so I guess the itemType system is screwed. So I swapped it with `itemClassID`, which works as expected. So glad thats fixed.

**Comment by tilkinsc** [comment]
Can you affirm that the indev branch works?

**Comment by hu71e** [comment]
i see someone else’s tooltip is fine, it maybe my client error.&nbsp;
i will try&nbsp;again when I have enough time.



发自我的iPhone


------------------ Original ------------------

**Comment by tilkinsc** [comment]
Well I did many commits, only one of which actually fixed the problem due to the strings I was comparing against was in chinese instead of english, so I had to convert to itemClassID.

**Comment by hu71e** [comment]
Nice work, iLvl now displays correctly.
In addition, I tested using the 'itemType=="武器"' code to run and also correctly display iLvl.
Thank you!

**Comment by tilkinsc** [comment]
Yes, that would make it run, as that would be like chinese version of Armor or Weapon
