### ISSUE TITLE
Translate frFR.lua strings

### ISSUE THREAD

**Issue by tilkinsc** [tilkinsc/KiwiItemInfo#20]
In `Locale/frFR.lua` strings aren't translated.

Dans `Locale/frFR.lua`, les chaînes ne sont pas traduites.

**Comment by beinganonymous** [comment]
@tilkinsc can i take this issue #20

**Comment by tilkinsc** [comment]
Appreciate it!

**Comment by tilkinsc** [comment]
Note the indev branch also has a `README_frFR.md`

**Comment by Tititesouris** [comment]
Some of this is Google Translated and there is also improper use of spaces with punctuation marks.
I'm going through it to fix the most obvious stuff, but not knowing the exact terminology used in-game I will refrain from modifying the actual translations (but I would recommend double-checking them)

**Comment by Tititesouris** [comment]
I already proposed a better version (#32 ) but to make sure it's good I have some questions:
COMMAND_HELP13: Should alwaysCompareItems be translated?
COMMAND_HELP15: I'm a bit confused by the phrasing. Is it saying that using the command with a parameter "num" of 5 will only show iLvls with a number of operations equal to 5?
COMMAND_SET_ERROR_BOOLEAN: Should the values in parentheses (true/false) be translated or kept in English as examples?
COMMAND_SEARCH_ARG_LEN: I don't understand what "to argument" is doing here
COMMAND_SEARCH_DONE1: I don't understand what "Kiwi so fly" is trying to say
KIWIII_SET: Is it a "set" of item, or "set"-ting something?

**Comment by tilkinsc** [comment]
Things in game that have to do with the api usually don't need translation. COMMAND_HELP* is displayed by command `/kiwiii help` so that the user can attain a quick info list of things they can do. alwaysCompareItems is a CVar, which can't be translated, as it's the same across the board of translations like all CVars. true and false are keywords specific to Lua and aren't translated between languages. The user must input true for enabling and false for disabling.

**Comment by tilkinsc** [comment]
Search arg length ... I think that is an error that happens when you don't supply enough arguments to the command. 

Kiwiii set does exactly how math would do. Set a equal to 5 for example.

**Comment by tilkinsc** [comment]
> I already proposed a better version (#32 ) but to make sure it's good I have some questions:

I'm gonna let you make changes and comment there when you are ready for me to R&M.

**Comment by Tititesouris** [comment]
Thank you, then I think I already got everything right but I will check again when I get home

**Comment by tilkinsc** [comment]
I will await.

**Comment by Tititesouris** [comment]
The original English of COMMAND_HELP15 is confusing and I can't figure out what it's trying to say, and thus can't translate it properly.
The original English of COMMAND_SEARCH_ARG_LEN is probably meant to be changed to "Kiwi Item Info: Invalid argument length", without the "to argument" part.

**Comment by tilkinsc** [comment]
It means the operation of $ with < > = and num

**Comment by tilkinsc** [comment]
COMMAND_SEARCH_ARG_LEN is invalid argument length, yes. This prints when you do an incomplete search. `/kiwiii search` yet it actually never execute because I with around it. So it's bug report.

**Comment by Tititesouris** [comment]
Thank you for the answers!
PR is now complete

**Comment by tilkinsc** [comment]
Ok I will review it.

**Comment by tilkinsc** [comment]
I requested a few changes, 1 is a might change if needed. Best labeled as testing needed.
