### ISSUE TITLE
How should the translation links look in README*.md?

### ISSUE THREAD

**Issue by tilkinsc** [tilkinsc/KiwiItemInfo#25]
Currently:
```
[English](README.md)  
[Español](README_esES.md)  
[Deutsch](README_deDE.md)  
[Português](README_ptBR.md)  
[Français](README_frFR.md)  
[Italiano](README_itIT.md)  
[한국어](README_koKR.md)  
[简体中文](README_zhCN.md)  
[繁體中文](README_zhTW.md)  
```

[English](README.md)  
[Español](README_esES.md)  
[Deutsch](README_deDE.md)  
[Português](README_ptBR.md)  
[Français](README_frFR.md)  
[Italiano](README_itIT.md)  
[한국어](README_koKR.md)  
[简体中文](README_zhCN.md)  
[繁體中文](README_zhTW.md)  

Could be:
```
[English](README.md) | [Español](README_esES.md) | [Deutsch](README_deDE.md) | [Português](README_ptBR.md) | [Français](README_frFR.md) | [Italiano](README_itIT.md) | [한국어](README_koKR.md) | [简体中文](README_zhCN.md) | [繁體中文](README_zhTW.md)  
```

[English](README.md) | [Español](README_esES.md) | [Deutsch](README_deDE.md) | [Português](README_ptBR.md) | [Français](README_frFR.md) | [Italiano](README_itIT.md) | [한국어](README_koKR.md) | [简体中文](README_zhCN.md) | [繁體中文](README_zhTW.md)

**Comment by beinganonymous** [comment]
@tilkinsc Second one looks good.

**Comment by tilkinsc** [comment]
Latter decided.

**Comment by tilkinsc** [comment]
I wanted to add flags to it like I do at https://github.com/tilkinsc/LuaConsole , but I only have /those/ flags and would have to obtain the same (free) flag archive I had.
