### ISSUE TITLE
Lua Error in 2.3.4

### ISSUE THREAD

**Issue by b-morgan** [tilkinsc/KiwiItemInfo#41]
The error below occurs in 2.3.4. I believe line 389 needs to be changed 
from:
	if(name and name:find("Character") ~= 1 or not name:find("Slot")) then
to:
	if(name and (name:find("Character") ~= 1 or not name:find("Slot"))) then

132x KiwiItemInfo\Tooltip.lua:389: attempt to index local 'name' (a nil value)
KiwiItemInfo\Tooltip.lua:389: in function `ShowEffectiveStats'
KiwiItemInfo\KiwiItemInfo-v2.3.4.lua:224: in function <KiwiItemInfo\KiwiItemInfo.lua:221>
[C]: ?
[C]: ?
[C]: in function `SetCompareItem'
FrameXML\GameTooltip.lua:716: in function <FrameXML\GameTooltip.lua:713>
(tail call): ?
FrameXML\GameTooltip.lua:545: in function <FrameXML\GameTooltip.lua:543>
[C]: ?
[C]: ?
[C]: ?
Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:498: in function <Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:492>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:424: in function `SetLootRollItem'
[string "*:OnEnter"]:2: in function <[string "*:OnEnter"]:1>

Locals:
tooltip = ShoppingTooltip1 {
 0 = <userdata>
 shownMoneyFrames = 1
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 TopOverlay = <unnamed> {
 }
 hasMoney = 1
 numMoneyFrames = 1
}
selection = <unnamed> {
 0 = <userdata>
 hasItem = 1
 Icon = <unnamed> {
 }
 Count = <unnamed> {
 }
}
name = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 hasItem = 1
 Icon = <unnamed> {
 }
 Count = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'name' (a nil value)"
att1 = nil
basic1 = nil
resist1 = nil
def1 = nil
L = <table> {
 TOOLTIP_UNIT = "Unit: "
 TOOLTIP_IC_DAMAGE_DELTA = " Damage (delta: "
 TOOLTIP_EX_AGI_M_AP = "Agility M. AP: "
 TOOLTIP_STACK = "Stack:"
 COMMAND_SEARCH_FAIL = "Kiwi couldn't find any items! :("
 COMMAND_HELP19 = "        * |cFFBBBBBBitemname|r -- search for items"
 TOOLTIP_ITEM_CONTRIB = "Stat Contribution:"
 TOOLTIP_PRY_DAMAGE = "DAMAGE"
 COMMAND_HELP17 = "        * |cFFBBBBBB@SubType|r -- shows by subtype (Mail, 1HSwords, 2HSwords, etc)"
 COMMAND_RESET = "Resetting KiwiItemInfo..."
 TOOLTIP_EX_AGI_R_AP = "Agility R. AP: "
 COMMAND_SET_ERROR_INDEX = "Kiwi needs a variable to set..."
 COMMAND_HELP14 = "    > |cFF888888search|r -- searches through item database for items"
 COMMAND_SEARCH_DONE1 = "Kiwi so cool. Kiwi so fly. kiwi found "
 TOOLTIP_CMP_AGILITY = "[+-]%d+%s[AGILITY]+"
 COMMAND_HELP13 = "    > |cFF888888aci|r -- toggles alwaysCompareItems CVar"
 TOOLTIP_CMP_DPS = "%(%d+%.%d+%s[DAMAGE PER SECOND]+%)"
 TOOLTIP_IC_STAMINA = "Stamina"
 COMMAND_VARS_DUMP = "Dumping user settings..."
 TOOLTIP_PRY_STRENGTH = "STRENGTH"
 COMMAND_SEARCH_TWO_HANDED = "Two-Handed "
 COMMAND_HELP9 = "    > |cFF888888vars|r -- shows all setting variables"
 TOOLTIP_IC_STRENGTH = "Strength"
 TOOLTIP_EX_RES_ARCANE = "Arcane Resist: "
 COMMAND_VARS_DONE = "All done!"
 TOOLTIP_IC_ARCANE = "Arcane Resistance"
 COMMAND_HELP11 = "        * |cFFBBBBBBvariable_name|r -- variable shown in /kiwiii vars"
 COMMAND_SET_ERROR_STRING = "Kiwi expects a string value (words). Sorry."
 COMMAND_SEARCH_ONE_HANDED = "One-Handed "
 COMMAND_HELP8 = "    > |cFF888888reset|r -- resets all saved variables, also reloads"
 KII_BAD_DB = "Kiwi's Item Info database wasn't loaded! Not using `/kiwiii search` command."
 TOOLTIP_IC_ARMOR = "Armor"
 COMMAND_HELP7 = "    > |cFF888888reload|r -- reloads addon"
 COMMAND_SEARCH_ARG_LEN = "Kiwi Item Info: Invalid argument length"
 TOOLTIP_PRY_EQUIP = "EQUIP: "
 KII_THANKS = "Kiwi thanks you for installing KiwiItemInfo v2.3.4! <3"
 TOOLTIP_EX_SPT_MP5 = "Spirit M/5: "
 TOOLTIP_EX_AGI_AR = "Agility Armor: "
 TOOLTIP_ITEM_

**Comment by tilkinsc** [comment]
Interesting, it shouldn't run if name is nil... what are you hovering over to make this happen? Well I guess it's broken because the or can still run and doesn't require name to be present. I'll shortly throw up a beta.

**Comment by tilkinsc** [comment]
Done. See curse forge.

**Comment by b-morgan** [comment]
Just in case you are still interested... I'm not exactly sure what I hovered over to make this happen 132 times but I believe it's things like quest rewards in the quest log, drops from mobs in instances, Instance drops in AtlasLoot, etc.

**Comment by tilkinsc** [comment]
Anything that has to do with not my addon will error because reused/modified assets make it so my addon receives modified or incorrect data, so the issue was a minor bug in logic in checking for existence before continuing. Quest rewards shouldn't proc any error naturally, as they just get appended a vendor price and item level. I am not sure if shift hover works on it hmm. Anyways, if you run into any more errors with the beta version let me know :)
