### ISSUE TITLE
Complete the translation in the zhcn.lua file

### ISSUE THREAD

**Issue by hu71e** [tilkinsc/KiwiItemInfo#42]
and, I've localized the strings in the UI panel.

[zhCN_KiwiItemInfo.zip](https://github.com/tilkinsc/KiwiItemInfo/files/3990955/zhCN_KiwiItemInfo.zip)

**Comment by tilkinsc** [comment]
Great now I have to translate it in other languages. Thanks. You should fork and PR the language file, at least to give you the [contributor] label.

**Comment by hu71e** [comment]
I'm not good at using the fork and PR feature. I'll try PR later.
I fixed a missing translation string in the zhCN.lua, please update it.
[zhCN.lua.zip](https://github.com/tilkinsc/KiwiItemInfo/files/3993262/zhCN.lua.zip)

**Comment by tilkinsc** [comment]
Thanks. I will make a beta release before I sleep. (just got off work) I got bored of adding the compat to the other translations so I am picking that back up now lol.
