### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by Comicus** [tilkinsc/KiwiItemInfo#44]
When mousing over items in chat I SOMETIMES get the following error:

4x KiwiItemInfo\Tooltip.lua:834: attempt to concatenate a nil value
KiwiItemInfo\Tooltip.lua:834: in function `ShowEffectiveStats'
KiwiItemInfo\KiwiItemInfo-v2.3.5-beta_002.lua:224: in function <KiwiItemInfo\KiwiItemInfo.lua:221>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetCompareItem'
FrameXML\GameTooltip.lua:716: in function <FrameXML\GameTooltip.lua:713>
(tail call): ?
FrameXML\GameTooltip.lua:545: in function <FrameXML\GameTooltip.lua:543>
[C]: ?
[C]: ?
...
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
MobInfo2-Classic\MI2_Events.lua:677: in function <MobInfo2-Classic\MI2_Events.lua:674>
[C]: ?
...eBartender4\libs\AceHook-3.0\AceHook-3.0-8.lua:95: in function <...eBartender4\libs\AceHook-3.0\AceHook-3.0.lua:87>
[C]: ?

Locals:
tooltip = ShoppingTooltip1 {
 0 = <userdata>
 SetCompareItem = <function> defined =[C]:-1
 updateTooltip = 0.200000
 hasMoney = 1
 PawnIconFrame = <unnamed> {
 }
 SetUnitAura = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 shownMoneyFrames = 1
 SetHyperlink = <function> defined =[C]:-1
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 numMoneyFrames = 1
 SetUnitDebuff = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
}
selection = <unnamed> {
 0 = <userdata>
 messageInfo = <table> {
 }
}
name = nil
_ = "Rogue"
_ = "ROGUE"
classID = 4
armor = 599
ch_agi = 84
_ = 84
ch_agi_pos = 26
ch_agi_neg = 0
ch_stm = 55
_ = 55
ch_stm_pos = 19
ch_stm_neg = 0
ch_str = 36
_ = 36
ch_str_pos = 2
ch_str_neg = 0
ch_int = 29
_ = 29
ch_int_pos = 1
ch_int_neg = 0
ch_spt = 37
_ = 37
ch_spt_pos = 8
ch_spt_neg = 0
agility_ap_melee = 0
agility_ap_range = 0
agility_crit = 0
agility_dodge = 0
agility_catform_ap_melee = 0
agility_armor = 0
eff_agility_armor = 0
stamina_health = 0
eff_stamina_health = 0
strength_ap_melee = 0
strength_block = 0
intellect_mana = 0
intellect_crit = 0
spirit_hpt = 0
spirit_mpt = 0
arcane_resist_p = 0
fire_resist_p = 2.857143
frost_resist_p = 0
nature_resist_p = 0
shadow_resist_p = 0
eff_arcane_resist_p = 0
eff_fire_resist_p = Infinite
eff_frost_resist_p = Infinite
eff_nature_resist_p = Infinite
eff_shadow_resist_p = Infinite
eff_agility_ap_melee = 0
eff_agility_ap_range = 0
eff_agility_crit = 0
eff_agility_dodge = 0
eff_agility_catform_ap_melee = 0
eff_strength_ap_melee = 0
eff_strength_block = 0
eff_intellect_mana = 0
eff_intellect_crit = 0
eff_spirit_hpt = 0
eff_spirit_mpt = 0
eff_armor = 60.100167
eff_agi = 0
eff_stm = 0
eff_str = 0
eff_int = 0
eff_spt = 0
queue = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
}
dirty = false
send_line = <function> defined @KiwiItemInfo\Tooltip.lua:692
blank_if_dirty = <function> defined @KiwiItemInfo\Tooltip.lua:696
(*temporary) = <function> defined @KiwiItemInfo\Tooltip.lua:692
(*temporary) = "Fire Resist: "
(*temporary) = <function> defined =[C]:-1
(*temporary) = "|cFFEFEF00%s|r"
(*temporary) = nil
(*temporary) = "%"
(*temporary) = "%d+%.?%d?%d?"
(*temporary) = nil
(*temporary) = <table> {
 1 = "Armor: |cFFEFEF0060.10%|r"
 2 = 1
 3 = 1
 4 = 1
 5 = false
}
(*temporary) = "Armor: |cFFEFEF0060.10%|r"
(*temporary) = "attempt to concatenate a nil value"
att1 = <table> {
 dps = 0
 max_dmg = 0
 min_dmg = 0
}
basic1 = <table> {
 Intellect = 0
 Agility = 0
 Stamina = 0
 Strength = 0
 Spirit = 0
}
resist1 = <table> {
 Shadow_Resist = 0
 Arcane_Resist = 0
 Nature_Resist = 0
 Frost_Resist = 0
 Fire_Resist = 12
}
def1 = <table> {
 Armor = 360
 Block = 0
 Durability = 0
}
L = <table> {
 VUI_SHOW_ILVL = "Show iLvl:"
 TOOLTIP_STACK = "Stack:"
 VUI_DEFAULT_ILVL_COLOR = "Default iLvl Coloration:"
 VUI_ITEM_ILVL = "Show iLvl On Items:"
 COMMAND_RESET = "Resetting KiwiItemInfo..."
 KIWIII_RESET = "reset"
 COMMAND_SEARCH_ONE_HANDED = "One-Handed "
 COMMAND_SEARCH_TWO_HANDED = "Two-Handed "
 TOOLTIP_EX_RES_ARCANE = "Arcane Resist: "
 TOOLTIP_IC_ARCANE = "Arcane Resistance"
 COMMAND_SET_ERROR_STRING = "Kiwi expects a string value (words). Sorry."
 TOOLTIP_EX_RES_SHADOW = "Shadow Resist: "
 COMMAND_SEARCH_ARG_LEN = "Kiwi Item Info: Invalid argument length"
 COMMAND_HELP3 = "Usage: /kiwiii [reload] [reset] [vars] [aci]"
 COMMAND_SEARCH_2H = "Two"
 TOOLTIP_EX_AGI_AR = "Agility Armor: "
 TOOLTIP_ITEM_COMPARE = "Kiwi says equipping will do this:"
 TOOLTIP_CMP_DURABILITY = "[DURABILITY]+%s%d+%s/%s%d+"
 TOOLTIP_CMP_DAMAGE = "%d+%s%-%s%d+%s[DAMAGE]+"
 COMMAND_SET_ERROR_VAR = "Kiwi doesn't have such a variable. Sorry."
 COMMAND_SET_ERROR_NUMBER = "Kiwi expects a number value. Sorry."
 KIWIII_HELP = "help"
 TOOLTIP_EX_AGI_M_CAT_AP = "Agility Catform AP: "
 COMMAND_HELP19 = "        * |cFFBBBBBBitemname|r -- search for items"
 KIWIII_SEARCH = "search"
 TOOLTIP_EX_STR_BLOCK = "Strength Block: "
 KIWIII_SET = "set"
 TOOLTIP_CMP_SHADOW = "[+-]%d+%s[SHADOW RESISTANCE

I really appreciate your work and wish I could help resolve issues, at my age it is hard to learn new tricks...

**Comment by tilkinsc** [comment]
Could you list all the plugins you were using and the plugin. As well as the item you were mousing over?

**Comment by Comicus** [comment]
There is no certain item that triggers the error, just passing over items in chat.

Date: 2020-01-13 00:58:57
ID: -1
Error occured in: Global
Count: ∞
Message: ..\AddOns\KiwiItemInfo\Tooltip.lua line 775:
   attempt to concatenate a nil value
Debug:
   KiwiItemInfo\Tooltip.lua:775: ShowEffectiveStats()
   KiwiItemInfo\KiwiItemInfo.lua:224:
      KiwiItemInfo\KiwiItemInfo.lua:221
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: SetCompareItem()
   ..\FrameXML\GameTooltip.lua:716:
      ..\FrameXML\GameTooltip.lua:713
   (tail call): ?
   ..\FrameXML\GameTooltip.lua:545:
      ..\FrameXML\GameTooltip.lua:543
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   MobInfo2-Classic\MI2_Events.lua:677:
      MobInfo2-Classic\MI2_Events.lua:674
   [C]: ?
   ...e\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:95:
      ...e\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:87
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: SetLootRollItem()
   [string "*:OnUpdate"]:3:
      [string "*:OnUpdate"]:1
Locals:
tooltip = ShoppingTooltip1 {
 0 = <userdata>
 SetCompareItem = <function> defined =[C]:-1
 numMoneyFrames = 1
 updateTooltip = 0.200000
 PawnIconFrame = <unnamed> {
 }
 SetUnitAura = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 shownMoneyFrames = 1
 SetHyperlink = <function> defined =[C]:-1
 SetUnitDebuff = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 needsReset = true
 SetUnitBuff = <function> defined =[C]:-1
 hasMoney = 1
}
selection = <unnamed> {
 0 = <userdata>
 hasItem = 1
 Icon = <unnamed> {
 }
 Count = <unnamed> {
 }
}
name = nil
_ = "Rogue"
_ = "ROGUE"
classID = 4
armor = 617
ch_agi = 93
_ = 93
ch_agi_pos = 33
ch_agi_neg = 0
ch_stm = 80
_ = 80
ch_stm_pos = 43
ch_stm_neg = 0
ch_str = 35
_ = 35
ch_str_pos = 0
ch_str_neg = 0
ch_int = 29
_ = 29
ch_int_pos = 1
ch_int_neg = 0
ch_spt = 40
_ = 40
ch_spt_pos = 10
ch_spt_neg = 0
agility_ap_melee = 0
agility_ap_range = 0
agility_crit = 0
agility_dodge = 0
agility_catform_ap_melee = 0
agility_armor = 0
eff_agility_armor = 0
stamina_health = 70
eff_stamina_health = 16.279070
strength_ap_melee = 3
strength_block = 0
intellect_mana = 0
intellect_crit = 0
spirit_hpt = 0
spirit_mpt = 0
arcane_resist_p = 0
fire_resist_p = 0
frost_resist_p = 0
nature_resist_p = 0
shadow_resist_p = 0
eff_arcane_resist_p = 0
eff_fire_resist_p = Infinite
eff_frost_resist_p = Infinite
eff_nature_resist_p = Infinite
eff_shadow_resist_p = Infinite
eff_agility_ap_melee = 0
eff_agility_ap_range = 0
eff_agility_crit = 0
eff_agility_dodge = 0
eff_agility_catform_ap_melee = 0
eff_strength_ap_melee = Infinite
eff_strength_block = 0
eff_intellect_mana = 0
eff_intellect_crit = 0
eff_spirit_hpt = 0
eff_spirit_mpt = 0
eff_armor = 14.424635
eff_agi = 0
eff_stm = 16.279070
eff_str = Infinite
eff_int = 0
eff_spt = 0
queue = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
}
dirty = true
send_line = <function> defined @Interface\AddOns\KiwiItemInfo\Tooltip.lua:692
blank_if_dirty = <function> defined @Interface\AddOns\KiwiItemInfo\Tooltip.lua:696
(*temporary) = <function> defined @Interface\AddOns\KiwiItemInfo\Tooltip.lua:692
(*temporary) = "Strength"
(*temporary) = ": "
(*temporary) = <function> defined =[C]:-1
(*temporary) = "%s"
(*temporary) = nil
(*temporary) = "%"
(*temporary) = "%d+%.?%d?%d?"
(*temporary) = nil
(*temporary) = "Stamina: 16.27%"
(*temporary) = "attempt to concatenate a nil value"
att1 = <table> {
 dps = 0
 max_dmg = 0
 min_dmg = 0
}
basic1 = <table> {
 Intellect = 0
 Agility = 0
 Stamina = 7
 Strength = 3
 Spirit = 0
}
resist1 = <table> {
 Shadow_Resist = 0
 Arcane_Resist = 0
 Nature_Resist = 0
 Frost_Resist = 0
 Fire_Resist = 0
}
def1 = <table> {
 Armor = 89
 Block = 0
 Durability = 0
}
L = <table> {
 VUI_SHOW_ILVL = "Show iLvl:"
 TOOLTIP_STACK = "Stack:"
 VUI_DEFAULT_ILVL_COLOR = "Default iLvl Coloration:"
 VUI_ITEM_ILVL = "Show iLvl On Items:"
 COMMAND_RESET = "Resetting KiwiItemInfo..."
 KIWIII_RESET = "reset"
 COMMAND_SEARCH_ONE_HANDED = "One-Handed "
 COMMAND_SEARCH_TWO_HANDED = "Two-Handed "
 TOOLTIP_EX_RES_ARCANE = "Arcane Resist: "
 TOOLTIP_IC_ARCANE = "Arcane Resistance"
 COMMAND_SET_ERROR_STRING = "Kiwi expects a string value (words). Sorry."
 TOOLTIP_EX_RES_SHADOW = "Shadow Resist: "
 COMMAND_SEARCH_ARG_LEN = "Kiwi Item Info: Invalid argument length"
 COMMAND_HELP3 = "Usage: /kiwiii [reload] [reset] [vars] [aci]"
 COMMAND_SEARCH_2H = "Two"
 TOOLTIP_EX_AGI_AR = "Agility Armor: "
 TOOLTIP_ITEM_COMPARE = "Kiwi says equipping will do this:"
 TOOLTIP_CMP_DURABILITY = "[DURABILITY]+%s%d+%s/%s%d+"
 TOOLTIP_CMP_DAMAGE = "%d+%s%-%s%d+%s[DAMAGE]+"
 COMMAND_SET_ERROR_VAR = "Kiwi doesn't have such a variable. Sorry."
 COMMAND_SET_ERROR_NUMBER = "Kiwi expects a number value. Sorry."
 KIWIII_HELP = "help"
 TOOLTIP_EX_AGI_M_CAT_AP = "Agility Catform AP: "
 COMMAND_HELP19 = "        * itemname -- search for items"
 KIWIII_SEARCH = "search"
 TOOLTIP_EX_STR_BLOCK = "Strength Block: "
 KIWIII_SET = "set"
 TOOLTIP_CMP_SHADOW = "[+-]%d+%s[SHADOW RESISTANCE]+"
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  ACP, v3.5.6 
  AlreadyKnown, v1.22
  AraBrokerGuildFriends, vr81
  AraBrokerReputations, vr34
  Armory, vv1.6.2
  Atlas, vv1.46.04.11303.01
  AtlasClassicWoW, vv1.45.01.11303.05
  AtlasTransportation, vv1.46.02.11303.00
  AtlasLootClassic, vv1.4.4
  AtlasLootClassicData, vv1.4.4
  AtlasLootClassicDungeonsAndRaids, vv1.4.4
  AtlasQuest, v4.11.59
  ATTClassic, v0.1.3
  Auctionator, v8.1.0
  AutoProfit, v1.13.2
  BagBrother, v
  Bagnon, v8.2.29
  BagnonArmory, v1.0.5
  Bartender4, v4.8.9
  BrokerClassicTracking, v1.1.1
  CharacterStatsClassic, v3.1
  ClassicTooltipItemLevel, v1.0.0
  CTBuffMod, v8.2.5.5
  CTCore, v8.2.5.9
  CTLibrary, v8.2.5.9
  CTMailMod, v8.2.5.9
  DBMCore, v1.13.29
  DBMDefaultSkin, v
  DBMPartyClassic, v
  DBMStatusBarTimers, v
  DefsToolbox, v80205.10
  DispellAlert, v8.0.9c
  GatherMate2, v1.45.5
  GSE, v2.4.25
  GSEGUI, v2.4.25
  GSELDB, v2.4.25
  GTFO, v4.51
  HandyNotes, vv1.5.9-1-g81432ff
  HandyNotesDungeonLocationsClassic, v1.03
  HandyNotesNPCsClassic, v1.21
  HandyNotesWorldMapButton, v11302.02-Classic
  InFlightLoad, v1.13.004
  ItemAutocomplete, v1.0.5
  ItemTooltipProfessionIcons, v1.1.5
  KiwiItemInfo, vv2.3.5-beta_002
  LeatrixMaps, v1.13.43
  LeatrixPlus, v1.13.44
  LibStub, v
  LibTouristClassic10, v
  LightHeaded, vv11302-1.0.0
  lsToasts, v11302.02
  Misspelled, v1.7.4
  MobInfo2Classic, v11302.04
  Molinari, v80200.64-Release
  MonkeySpeed, vv3.4.0
  OmniCC, v8.3.1
  Pawn, v2.3.15
  QuestAnnounce, v8.0.2.1
  QuestCompletist, v109.25
  Quester, v1.13.2.1
  QuestFrameFixer, v1.1.1
  Questie, v5.5.1
  RealMobHealth, v2.18
  RecipeRadarClassic, v1.0.0.23
  Recount, vv1.13.3a
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SimpleDing, vv1.1.1
  SimpleItemLevel, v1
  SkilletClassic, vr140
  SpeedyAutoLoot, v2.0.25
  SpellbookAbridged, v2.6.2
  TFTB, v1.10
  TidyMinimapClassic, v1.0
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanAttributesMulti, v1.1
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicItemDed, v1.0.0.3
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicRestPlus, v1.0.0.1
  TitanProfessionsMulti, v1.3
  TomTom, vv11303-1.0.9
  UsedInRecipe, v1.0.3
  WhatsTraining, v1.8.7
  WhereToGatherClassic, v1.0
  WideQuestLog, v
  ZoneInfoClassic, v1.0
  ZPerl, v5.8.9
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=ab1)

**Comment by tilkinsc** [comment]
Can you confirm this bug is still in v2.3.5?
