### ISSUE TITLE
Bug with item compare

### ISSUE THREAD

**Issue by Healarybuf** [tilkinsc/KiwiItemInfo#45]
Hey, I'm having an issue for some days now.

For some reason, I can no longer compare stats for items, except for rings and trinkets.

Here is a screenshot to show the problem.

 

https://imgur.com/a/fROua6r

**Comment by tilkinsc** [comment]
Is there any errors?

**Comment by Healarybuf** [comment]
I did not find any LUA errors when trying to compare items.
I noticed that when I press shift on items I currently have equipped, Kiwi does show the stat contribution.
![WoWScrnShot_040521_094348](https://user-images.githubusercontent.com/81938961/113580850-4d843180-95f4-11eb-82f3-7b1072712029.jpg)


Also, I tried 3 troubleshooting things: I tried disabling ALL other addons except for Kiwi, I tried uninstalling the addon and reinstalling, and finally, I tried version 2.3.4 instead of 2.3.5. All the attempts resulted in the same problem.
And Kiwi does work for Neck, Rings and Trinkets.

**Comment by Healarybuf** [comment]
You can hit me up on discord if you want to test things out. Healarybuf#0375
Also, I love your addon, I'm willing to donate some money on Paypal if you can fix it :)

**Comment by tilkinsc** [comment]
You tried the latest beta?

**Comment by Healarybuf** [comment]
![Screenshot 2021-04-05 223458](https://user-images.githubusercontent.com/81938961/113650992-2a429c00-965f-11eb-9d02-8245e166840e.jpg)

I just did and it still doesn't work.

It still does work on trinkets, ring and neck.

**Comment by tilkinsc** [comment]
That is an invalid discord name, you need 4 numbers.

**Comment by Healarybuf** [comment]
For some reason, when pasting the Discord ID on here it removes the 0 in the number....
![image](https://user-images.githubusercontent.com/81938961/113715187-322e2a80-96b7-11eb-8932-e36aee95488d.png)
Healarybuf#0375
![image](https://user-images.githubusercontent.com/81938961/113715358-6a356d80-96b7-11eb-92df-6de76a0d6b85.png)

with a space it works, Healarybuf# 0375
