### ISSUE TITLE
Create an optional GUI settings pane in place of argumentless kiwiii command

### ISSUE THREAD

**Issue by tilkinsc** [tilkinsc/KiwiItemInfo#5]
Pro: You don't have to use the command to set or view vars
Con: Compatibility support between UI overhauls (already a problem)

**Comment by idl0r** [comment]
Advanced Interface Options seems decent. Not sure if it requires it's own API or kind of, or if that's Blizzard standard. Would be cool though.

**Comment by tilkinsc** [comment]
The user manages their own using the command currently. Not sure what AIO is

**Comment by tilkinsc** [comment]
There is another con, it also adds a bit of bulk

**Comment by tilkinsc** [comment]
I'll start this after work.

**Comment by tilkinsc** [comment]
~~Ok I am working on it now~~ I couldn't find the template that I used before, and I can't find any templates online. So it's a bit stalled here. Open to suggestions.

I _MAY_ use Ace on this one, as it goes with other addons quite nicely, but I really don't wanna.
